version: '3.9'

services:
  payload:
    image: node:22-alpine

    ports:
      - '3000:3000'
      - '9229:9229'

    working_dir: /app

    volumes:
      - .:/app
      - node_modules:/app/node_modules

    env_file:
      - .env

    environment:
      NODE_ENV: development

    depends_on:
      - postgres

    command: >
      sh -c "
      corepack enable &&
      corepack prepare pnpm@10.5.2 --activate &&
      pnpm install &&
      pnpm dev
      "

  postgres:
    image: postgres:17

    ports:
      - '5432:5432'

    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: payload

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
